repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.10
